# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JfZ0WVSbMEybczORQFYRHqMGhpyJwFFh
"""

print("Calculate analysis")
print("Unit conversion")
print("Drawing graps")
Q1=input("Select the action you want to take")
if Q1=="Calculate analysis":
  print("Choose on of the parameters.")
  print("BOD\COD\Conductivity\Amount of suspended solid\Cr\pH")
  Q2=input("Select the parameter you will process?")
  if Q2=="BOD":
    DO1=float(input("İnitial amount of dissolved oxygen (mg/L)"))
    DO2=float(input("amount of dissolved oxygen after a certain period of time(mg/L)"))
    time_period=float(input("period examined(day):"))
    BOD=(((DO1-DO2)/time_period)*100)
    print("BOD result is", BOD)
  if Q2=="COD":
    A=float(input("Amount of iron ammonium sulfate solution used for the blank sample(mL)"))
    B=float(input("Amount of iron ammonium sulfate solution used for the sample(mL)"))
    N=float(input("Normality of iron ammonium sulfate solution"))
    ml_numune=float(input("Volume of sample"))
    COD=(((A-B)*N*8000)/ml_numune)
    print("COD result is" , COD)
  if Q2=="Conductivity":
    R=float(input("Enter the resisdance:"))
    Conductivity=(1/R)
    print("Conductivity result is", Conductivity)
  if Q2=="Amount of suspended solid":
    C=float(input("First weighing"))
    D=float(input("Second weighing"))
    V=float(input("Volume"))
    SS=(((D-C)*1000)/V)
    print("Amount of suspended solid result is", SS)
  if Q2=="Cr":
    X=float(input("Volume of sample"))
    Cr=(((1/1000)*100)/X)
    print("Cr+6 result is", Cr)
  if Q2=="pH":
    Y=float(input("Enter the pH value:"))
    if Y<7:
      print("acid")
    if Y>7:
      print("base")
    if Y==7:
      print("nötr")
if Q1=="Unit conversion":
  print("Choose on of the parameters.")
  print("kg or g \ g/mL or mg/L \ Celcius or Fahrenheit \ Kelvin or Celcius")
  Q3=input("Which unit conversion system do you want to use?")
  if Q3=="kg or g":
    weight=float(input("Enter an amount."))
    unit=input("kilograms or grams? (kg or g):")
    if unit=="g":
      weight=weight/1000
      unit="kg."
    elif unit=="kg":
     weight=weight*1000
     unıt="g."
    print("Weight result is", weight)
  if Q3=="g/mL or mg/L":
    A=float(input("Enter solution amount"))
    unit=input("g/mL or mg/L?")
    if unit=="g/mL":
      A=(A*1000000)
      unit="mg/L."
      print("The solution amount is", A)
    elif unit=="mg/L":
      A=A/1000000
      unit="g/mL."
      print("The solution amount is", A )
  if Q3=="Celcius or Fahrenheit":
   unit=input("Is this temperature in Celcius or Fahrenheit? (C/F):")
   temp=float(input("Enter the temperature:"))
  if unit=="C":
   temp=round(((9*temp)/5)+32,1)
   print("The temperature in Fahrenheit is" , temp)
  elif unit=="F":
   temp=round(((temp-32)*5)/9,1)
   print("The temperature in Celcius is", temp)
  if Q3=="Kelvin or Celcius":
   unit=input("Kelvin or Celcius? (K or C?)")
   temperature=float(input("Enter the temperature."))
  if unit=="C":
     temperature=(temperature+273,15)
     unit="K."
     print("The temperature is", temperature, "K")
  elif unit=="K":
    temperature=(temperature-273,15)
    unit="C."
    print("The temperature is", temperature, "C")
if Q1=="Drawing graps":
  print("Choose on of the parameters.")
  print("Line chart \ dot chart")
  Q4=input("Choose which type of chart you want to draw")
  if Q4=="Line chart":
      import matplotlib.pyplot as plt
      x_values=[1,2,3,4,5]
      y_values=[2,4,6,8,10]
      plt.plot(x_values, y_values, color='green', marker='o', linestyle='-', linewidth=2, markersize=8)
      plt.title('Line Plot Example')
      plt.show()
  if Q4=="Dot chart":
    import matplotlib.pyplot as plt
    import numpy as np
    np.random.seed(42)
    x_values=np.random.rand(20)
    y_values=np.random.rand(20)
    plt.scatter(x_values, y_values, color='blue', marker='o', s=50)
    plt.title('Scatter Plot Example')
    plt.show()



